version: "3.5"

services:
  # cuda-ubuntu_1:
  #   container_name: cuda-ubuntu_1
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "6970:22"
  #   restart: always
  #   devices:
  #     - /dev/nvidiactl
  #     - /dev/nvidia-uvm
  #     - /dev/nvidia0
  #   tty: true
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             capabilities: [ gpu, utility, compute, video ]
  #   networks:
  #     container-link:
  #       ipv4_address: 172.20.0.1
  #    sysctls:
  #        - /proc/sys/net/ipv4/tcp_wmem
  #        - /proc/sys/net/ipv4/tcp_rmem
  #        - net.core.rmem_default=10000000
  #        - net.core.wmem_default=10000000
  #        - net.core.rmem_max=10000000
  #        - net.core.wmem_max=10000000
  cuda-ubuntu_2:
    container_name: cuda-ubuntu_2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6971:22"
    restart: always
    devices:
      - /dev/nvidiactl
      - /dev/nvidia-uvm
      - /dev/nvidia0
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu, utility, compute, video ]
    networks:
      container-link:
        ipv4_address: 172.20.0.2

  cuda-ubuntu_3:
    container_name: cuda-ubuntu_3
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6972:22"
    restart: always
    devices:
      - /dev/nvidiactl
      - /dev/nvidia-uvm
      - /dev/nvidia0
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu, utility, compute, video ]
    networks:
      container-link:
        ipv4_address: 172.20.0.3

  cuda-ubuntu_4:
    container_name: cuda-ubuntu_4
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6973:22"
    restart: always
    devices:
      - /dev/nvidiactl
      - /dev/nvidia-uvm
      - /dev/nvidia0
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu, utility, compute, video ]
    networks:
      container-link:
        ipv4_address: 172.20.0.4

  cuda-ubuntu_5:
    container_name: cuda-ubuntu_5
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6974:22"
    restart: always
    devices:
      - /dev/nvidiactl
      - /dev/nvidia-uvm
      - /dev/nvidia0
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu, utility, compute, video ]
    networks:
      container-link:
        ipv4_address: 172.20.0.5

  cuda-ubuntu_6:
    container_name: cuda-ubuntu_6
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6975:22"
    restart: always
    devices:
      - /dev/nvidiactl
      - /dev/nvidia-uvm
      - /dev/nvidia0
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu, utility, compute, video ]
    networks:
      container-link:
        ipv4_address: 172.20.0.6

  cuda-ubuntu_7:
    container_name: cuda-ubuntu_7
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6976:22"
    restart: always
    devices:
      - /dev/nvidiactl
      - /dev/nvidia-uvm
      - /dev/nvidia0
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu, utility, compute, video ]
    networks:
      container-link:
        ipv4_address: 172.20.0.7

  cuda-ubuntu_8:
    container_name: cuda-ubuntu_8
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6977:22"
    restart: always
    devices:
      - /dev/nvidiactl
      - /dev/nvidia-uvm
      - /dev/nvidia0
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu, utility, compute, video ]
    networks:
      container-link:
        ipv4_address: 172.20.0.8

  cuda-ubuntu_9:
    container_name: cuda-ubuntu_9
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6978:22"
    restart: always
    devices:
      - /dev/nvidiactl
      - /dev/nvidia-uvm
      - /dev/nvidia0
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu, utility, compute, video ]
    networks:
      container-link:
        ipv4_address: 172.20.0.9

  cuda-ubuntu_10:
    container_name: cuda-ubuntu_10
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6979:22"
    restart: always
    devices:
      - /dev/nvidiactl
      - /dev/nvidia-uvm
      - /dev/nvidia0
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu, utility, compute, video ]
    networks:
      container-link:
        ipv4_address: 172.20.0.10

  cuda-ubuntu_11:
    container_name: cuda-ubuntu_11
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6980:22"
    restart: always
    devices:
      - /dev/nvidiactl
      - /dev/nvidia-uvm
      - /dev/nvidia0
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu, utility, compute, video ]
    networks:
      container-link:
        ipv4_address: 172.20.0.11

  cuda-ubuntu_12:
    container_name: cuda-ubuntu_12
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6981:22"
    restart: always
    devices:
      - /dev/nvidiactl
      - /dev/nvidia-uvm
      - /dev/nvidia0
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu, utility, compute, video ]
    networks:
      container-link:
        ipv4_address: 172.20.0.12

  cuda-ubuntu_13:
    container_name: cuda-ubuntu_13
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6982:22"
    restart: always
    devices:
      - /dev/nvidiactl
      - /dev/nvidia-uvm
      - /dev/nvidia0
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu, utility, compute, video ]
    networks:
      container-link:
        ipv4_address: 172.20.0.13

  cuda-ubuntu_14:
    container_name: cuda-ubuntu_14
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6983:22"
    restart: always
    devices:
      - /dev/nvidiactl
      - /dev/nvidia-uvm
      - /dev/nvidia0
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu, utility, compute, video ]
    networks:
      container-link:
        ipv4_address: 172.20.0.14

  cuda-ubuntu_15:
    container_name: cuda-ubuntu_15
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6984:22"
    restart: always
    devices:
      - /dev/nvidiactl
      - /dev/nvidia-uvm
      - /dev/nvidia0
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu, utility, compute, video ]
    networks:
      container-link:
        ipv4_address: 172.20.0.15

  cuda-ubuntu_16:
    container_name: cuda-ubuntu_16
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6985:22"
    restart: always
    devices:
      - /dev/nvidiactl
      - /dev/nvidia-uvm
      - /dev/nvidia0
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu, utility, compute, video ]
    networks:
      container-link:
        ipv4_address: 172.20.0.16

  cuda-ubuntu_17:
    container_name: cuda-ubuntu_17
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6986:22"
    restart: always
    devices:
      - /dev/nvidiactl
      - /dev/nvidia-uvm
      - /dev/nvidia0
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu, utility, compute, video ]
    networks:
      container-link:
        ipv4_address: 172.20.0.17

  cuda-ubuntu_18:
    container_name: cuda-ubuntu_18
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6987:22"
    restart: always
    devices:
      - /dev/nvidiactl
      - /dev/nvidia-uvm
      - /dev/nvidia0
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu, utility, compute, video ]
    networks:
      container-link:
        ipv4_address: 172.20.0.18

  cuda-ubuntu_19:
    container_name: cuda-ubuntu_19
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6988:22"
    restart: always
    devices:
      - /dev/nvidiactl
      - /dev/nvidia-uvm
      - /dev/nvidia0
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu, utility, compute, video ]
    networks:
      container-link:
        ipv4_address: 172.20.0.19

  cuda-ubuntu_20:
    container_name: cuda-ubuntu_20
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6989:22"
    restart: always
    devices:
      - /dev/nvidiactl
      - /dev/nvidia-uvm
      - /dev/nvidia0
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu, utility, compute, video ]
    networks:
      container-link:
        ipv4_address: 172.20.0.20

  cuda-ubuntu_21:
    container_name: cuda-ubuntu_21
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6990:22"
    restart: always
    devices:
      - /dev/nvidiactl
      - /dev/nvidia-uvm
      - /dev/nvidia0
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu, utility, compute, video ]
    networks:
      container-link:
        ipv4_address: 172.20.0.21

  cuda-ubuntu_22:
    container_name: cuda-ubuntu_22
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6991:22"
    restart: always
    devices:
      - /dev/nvidiactl
      - /dev/nvidia-uvm
      - /dev/nvidia0
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu, utility, compute, video ]
    networks:
      container-link:
        ipv4_address: 172.20.0.22

  cuda-ubuntu_23:
    container_name: cuda-ubuntu_23
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6992:22"
    restart: always
    devices:
      - /dev/nvidiactl
      - /dev/nvidia-uvm
      - /dev/nvidia0
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu, utility, compute, video ]
    networks:
      container-link:
        ipv4_address: 172.20.0.23

  cuda-ubuntu_24:
    container_name: cuda-ubuntu_24
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6993:22"
    restart: always
    devices:
      - /dev/nvidiactl
      - /dev/nvidia-uvm
      - /dev/nvidia0
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu, utility, compute, video ]
    networks:
      container-link:
        ipv4_address: 172.20.0.24

  cuda-ubuntu_25:
    container_name: cuda-ubuntu_25
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6994:22"
    restart: always
    devices:
      - /dev/nvidiactl
      - /dev/nvidia-uvm
      - /dev/nvidia0
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu, utility, compute, video ]
    networks:
      container-link:
        ipv4_address: 172.20.0.25

  cuda-ubuntu_26:
    container_name: cuda-ubuntu_26
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6995:22"
    restart: always
    devices:
      - /dev/nvidiactl
      - /dev/nvidia-uvm
      - /dev/nvidia0
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu, utility, compute, video ]
    networks:
      container-link:
        ipv4_address: 172.20.0.26

  cuda-ubuntu_27:
    container_name: cuda-ubuntu_27
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6996:22"
    restart: always
    devices:
      - /dev/nvidiactl
      - /dev/nvidia-uvm
      - /dev/nvidia0
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu, utility, compute, video ]
    networks:
      container-link:
        ipv4_address: 172.20.0.27

  cuda-ubuntu_28:
    container_name: cuda-ubuntu_28
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6997:22"
    restart: always
    devices:
      - /dev/nvidiactl
      - /dev/nvidia-uvm
      - /dev/nvidia0
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu, utility, compute, video ]
    networks:
      container-link:
        ipv4_address: 172.20.0.28

  cuda-ubuntu_29:
    container_name: cuda-ubuntu_29
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6998:22"
    restart: always
    devices:
      - /dev/nvidiactl
      - /dev/nvidia-uvm
      - /dev/nvidia0
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu, utility, compute, video ]
    networks:
      container-link:
        ipv4_address: 172.20.0.29

  cuda-ubuntu_30:
    container_name: cuda-ubuntu_30
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6999:22"
    restart: always
    devices:
      - /dev/nvidiactl
      - /dev/nvidia-uvm
      - /dev/nvidia0
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu, utility, compute, video ]
    networks:
      container-link:
        ipv4_address: 172.20.0.30

#ネットワーク定義
networks:
  # docker-composeで勝手にデフォルトネットワークが生成される予防。（自動で全コンテナが所属するbridgeを指定）
  default:
    external:
      name: bridge
  # コンテナ間通信用のネットワークセグメント
  container-link:
    # これが作成されるネットワーク名（同名がなければ自動生成される）
    name: docker.nln.internal
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
