version: '3.5'

services:
  ubuntu:
    container_name: ubuntu_1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "6970:22"
    restart: always
#    volumes:
#        - "/proc:/proc"
#        - "../cefore:/home/docker/cefore"
    networks:
      - container-link
#    sysctls:
#        - /proc/sys/net/ipv4/tcp_wmem
#        - /proc/sys/net/ipv4/tcp_rmem
#        - net.core.rmem_default=10000000
#        - net.core.wmem_default=10000000
#        - net.core.rmem_max=10000000
#        - net.core.wmem_max=10000000

# ネットワーク定義
networks:
  # docker-composeで勝手にデフォルトネットワークが生成される予防。（自動で全コンテナが所属するbridgeを指定）
  default:
    external:
      name: bridge
  # コンテナ間通信用のネットワークセグメント
  container-link:
    # これが作成されるネットワーク名（同名がなければ自動生成される）
    name: docker.internal
